// template/app/__react/containers/Root/index.js
import React, { Component } from 'react';
import { hot } from 'react-hot-loader'; //eslint-disable-line import/no-extraneous-dependencies

import styles from './root.scss';

class Root extends Component {

    render() {

        return (
            <div className={styles.root}>
                Hello World
            </div>
        );
    }

}

export default hot(module)(Root);

export { Root };

// template/app/__vue/containers/Root/index.vue
<template>
    <div :class="$style.root">
        Hello \{{ message }}
    </div>
</template>

<script>

export default {
    name: 'Root',

    data() {
        return {
            message: 'World'
        };
    }
};

</script>

<style lang="scss" module>
@import "mixins";

.root {
    font-size: font-size(13px);
}
</style>
